server:
  port: 8086
  servlet:
    context-path: '/delivery'

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=delivery
      username: delivery
      password: qwerty123
    artemis:
      host: localhost
      port: 61616
      user: artemis
      password: password
      mode: native

app.basePath: /delivery