server:
  port: 8086
  servlet:
    context-path: '/delivery'

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=delivery
      username: delivery
      password: qwerty123
    rabbitmq:
      host: localhost
      port: 5672
      username: rabbit
      password: rabbit
    redis:
      host: localhost
      port: 6379


app.basePath: /delivery
users.url: http://localhost:8081/users